.include <bsd.own.mk>

.if ${MACHINE_ARCH} == "earm"
SUBDIR+=	eepromread
.endif # ${MACHINE_ARCH} == "earm"

SUBDIR+=	diff
SUBDIR+=	grep
SUBDIR+=	mined
SUBDIR+=	ministat
SUBDIR+=	mtop
SUBDIR+=	toproto
SUBDIR+=	trace
SUBDIR+=	syscalltest
SUBDIR+=	receive_test_0
SUBDIR+=	send_test_0
SUBDIR+=	receive_test_1
SUBDIR+=	send_test_1
SUBDIR+=	recover_test_0
SUBDIR+=	openwait_test_0
SUBDIR+=	deadlock_test_0
SUBDIR+=	no_group_test_0
SUBDIR+=	kill_test_0
SUBDIR+=	kill_test_1
SUBDIR+=	kill_test_2
SUBDIR+=	kill_test_3
SUBDIR+=	kill_test_4
SUBDIR+=	kill_test_5



.include <bsd.subdir.mk>
